# coupling design
coupling_design: 
  - "interleaved"
permutation: "fixed"
num_coupling_layers: 
  - 12
  - 15
# training
epochs: 50
batch_size: 256
early_stopping: False
learning_rate: 0.001
optimizer_name: "AdamW"
lr_scheduler_name: "CosineDecay"
reg_val: 
  - 10
  - 1
  - 0
  - 0.1
# affine or interleaved only
affine_units_per_dense_layer:
  - 256
  - 512
affine_num_dense_layers: 
  - 2
  - 5
  - 10
affine_activation: "relu"
affine_dropout: False
affine_mc_dropout: False
affine_dropout_prob: 0.05
# spline or interleaved only
spline_units_per_dense_layer:
  - 256
  - 512
spline_num_dense_layers: 
  - 2
  - 5
  - 10
spline_activation: "relu"
spline_dropout: True
spline_mc_dropout: True
spline_dropout_prob:
  - 0.1
  - 0.05
spline_bins:
  - 8
  - 16

