name: architecture search for Gaussian benchmark
description: try different parameters to optimise Gaussian benchmark
program: /scripts/innfer_sweep.py
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  activation:
    value: [ "relu" ]
  learning_rate:
    values: [ 0.01, 0.1 ]
  optimizer_name:
    value: [ "Adam" ]
  num_coupling_layer:
    values: [ 4, 8 ]
  units_per_coupling_layer:
    values: [ 64, 128 ]
  num_dense_layers:
    values: [ 2, 4 ]
  batch_size:
    value: 64
  dropout:
    value: True
  mc_dropout:
    value: True
  lr_scheduler_name:
    value: "ExponentialDecay"
  lr_scheduler_options:
    value: { decay_rate: 0.5 }
  early_stopping:
    value: True
  coupling_design:
    value: "interleaved"
  permutation:
    value: "learnable"
  epochs:
    value: 10
#command:
#  - ${env}
#  - ${interpreter}
#  - ${program}
#  - --step="Train" --benchmark="Gaussian"