# Train models
- step: "Train"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    disable_tqdm: True

# Get performance metrics
- step: "PerformanceMetrics"
  submit: "configs/submit/condor_gpu.yaml"  

# Make generation plots
- step: "Generator"
  submit: "configs/submit/condor_2_cpus_avx.yaml"
- step: "GeneratorSummary"
  submit: "configs/submit/condor_2_cpus_avx.yaml"

# Get validation results
- step: "InitialFit"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "Validation"
    points_per_job: 6
- step: "BestFitDistributions"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "Validation"
- step: "Hessian"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "Validation"
    points_per_job: 6
- step: "DMatrix"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "Validation"
    points_per_job: 6
- step: "CovarianceWithDMatrix"
  submit: "configs/submit/condor_avs.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "Validation"

# Get asimov results
- step: "MakeAsimov"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
    points_per_job: 6
- step: "InitialFit"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
    points_per_job: 6
- step: "BestFitDistributions"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
- step: "Hessian"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
    points_per_job: 6
- step: "Covariance"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"

# Get full summary
- step: "Summary"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    extra_infer_dir_name: "Asimov"
    summary_from: "Covariance"
    summary_nominal_name: "Asimov"
    summary_show_2sigma: True
    other_input : "Validation:CovarianceWithDMatrixValidation:covariancewithdmatrix_results"