# Make generation plots
- step: "Generator"
  submit: "configs/submit/condor_2_cpus_avx.yaml"
  split_validation_files: True
  likelihood_type: "unbinned_extended"

# Get validation results from full fit
- step: "InitialFit"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "ClosureTest"
    points_per_job: 12
    split_validation_files: True
    likelihood_type: "unbinned_extended"
- step: "Hessian"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "ClosureTest"
    points_per_job: 12
    split_validation_files: True
    likelihood_type: "unbinned_extended"
- step: "DMatrix"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "ClosureTest"
    points_per_job: 12
    split_validation_files: True
    likelihood_type: "unbinned_extended"
- step: "CovarianceWithDMatrix"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "ClosureTest"
    split_validation_files: True
    likelihood_type: "unbinned_extended"

# Get validation results from freezing all other parameters
- step: "InitialFit"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "ClosureTestFrozen"
    points_per_job: 12
    split_validation_files: True
    freeze: "all-but-one"
    likelihood_type: "unbinned_extended"
- step: "Hessian"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "ClosureTestFrozen"
    points_per_job: 12
    split_validation_files: True
    freeze: "all-but-one"
    likelihood_type: "unbinned_extended"
- step: "DMatrix"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "ClosureTestFrozen"
    points_per_job: 12
    split_validation_files: True
    freeze: "all-but-one"
    likelihood_type: "unbinned_extended"
- step: "CovarianceWithDMatrix"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    data_type: "sim"
    extra_infer_dir_name: "ClosureTestFrozen"
    split_validation_files: True
    freeze: "all-but-one"
    likelihood_type: "unbinned_extended"
- step: "SummaryAllButOneCollect"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    extra_infer_dir_name: "ClosureTestFrozen"
    summary_from: "CovarianceWithDMatrix"
    likelihood_type: "unbinned_extended"

# Get asimov results
- step: "MakeAsimov"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
    points_per_job: 6
- step: "InitialFit"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
    points_per_job: 6
    likelihood_type: "unbinned_extended"
- step: "Hessian"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
    points_per_job: 6
    likelihood_type: "unbinned_extended"
- step: "Covariance"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
    likelihood_type: "unbinned_extended"

# Get full summary
- step: "Summary"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    extra_infer_dir_name: "Asimov"
    summary_from: "Covariance"
    summary_nominal_name: "Asimov"
    summary_show_2sigma: True
    summary_subtract: True
    loop_over_nuisances: True
    other_input : "Closure Test:CovarianceWithDMatrixClosureTest:covariancewithdmatrix_results,Closure Test (Others Frozen):CovarianceWithDMatrixClosureTestFrozen:covariancewithdmatrix_results"